services:

  airflow-worker:
    image: apache/airflow:3.2.0
    container_name: airflow_worker
    command: celery worker
    restart: always
    env_file:
      - ../.env.worker
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD-SHELL", "airflow celery worker --help > /dev/null 2>&1"]
      interval: 30s
      retries: 5
      start_period: 30s
